name = "iso"
description = "ISO Standard references for Ada such as 1366 & 4217 (Country & Currency)"
version = "2.0.0"
licenses = "MIT"
website = "https://github.com/ada-iso/ada_iso/"
tags = [ "countries", "currencies", "iso-1366", "iso-4217" ]

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["AJ-Ianozi"]
