name = "iso_countries"
description = "ISO 3166 reference for Ada"
version = "0.2.0-dev"
licenses = "MIT"

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["aj-ianozi"]

[build-switches]
"*".ada_version = "Ada2022"
